#usado para os inputs de usuários
TRADUCOES = {
    'mirage': {
        'Window':           ['window', 'janela', 'janelao', 'janelão'],
        'Short':            ['short', 'curto', 'l'],
        'Connector':        ['connector', 'conector', 'conect', 'ligação', 'ligacao'],
        'Catwalk':          ['catwalk', 'passarela', 'varanda'],
        'Jungle':           ['jungle', 'mato'],
        'Stairs':           ['stairs', 'escada', 'cabecinha', 'cabeçinha'],
        'Palace':           ['palace', 'palacio', 'palácio'],
        'Ramp':             ['ramp', 'caverna'],
        'B Site':           ['bsite', 'b site', 'b', 'bomb b', 'bomba b'],
        'A Site':           ['asite', 'a site', 'a', 'bomb a', 'bomba a'],
        'Top Mid':          ['topmid', 'top mid', 'topo'],
        'Apps':             ['apps', 'tapete', 'apartamento'],
        'Deep Apps':        ['deep apps', 'deepapps', 'cozinha', 'fundo apps'],
        'Kitchen Door':     ['kitchen door', 'porta do mercado', 'porta mercado'],
        'Kitchen Window':   ['kitchen window', 'janela do mercado'],
        'Left Arch':        ['left arch', 'arco esquerdo', 'arco da esquerda'],
        'Right Arch':       ['right arch', 'arco direito', 'arco da direita'],
        'Jungle+Connector': ['jungle+connector', 'mato+conector', 'passagem'],
        'Tetris':           ['tetris'],
        'Ticket':           ['ticket', 'boltz', 'base'],
        'Firebox':          ['firebox', 'caixa de fogo', 'fogo'],
        'Ladder Room':      ['ladder room', '3d', 'moscow', 'moscowfive', 'moscow five'],
        'Mid Boxes':        ['mid boxes', 'carroça', 'carroca'],
        'Mid':              ['mid', 'meio'],
        'Over Chair':       ['over chair', 'cadeira'],
        'Over Palm':        ['over palm', 'palmeira'],
        'Over Ramp':        ['over ramp', 'rampa', 'cima da rampa'],
        'Underpass':        ['underpass', 'caminho de rato', 'rato'],
        'Dark':             ['dark', 'areia'],
        'Sandwitch':        ['sandwitch', 'sanduiche'],
        'Bench':            ['bench', 'banco'],
    },
    'overpass': {
        'Bank':             ['bank', 'banco'],
        'Bridge':           ['bridge', 'passagem'],
        'Heaven':           ['heaven', 'ceu', 'céu', 'janela'],
        'Monster':          ['monster', 'sapao', 'sapão'],
        'Toilets':          ['toilets', 'banheiro'],
        'Trash':            ['trash', 'lixo', 'lixeira'],
        'B Backsite':       ['b backsite', 'piscina'],
        'B Site':           ['b site', 'bsite', 'b', 'bomb b', 'bomba b'],
        'A Site':           ['a site', 'asite', 'a', 'bomb a', 'bomba a'],
        'Truck':            ['truck', 'caminhao', 'caminhão'],
        'Connector Doors':  ['connector doors', 'ligacao', 'ligação'],
        'Monster Exit':     ['monster exit', 'saida do sapao', 'saída do sapão'],
        'Main Stairs':      ['main stairs', 'entrada da a', 'entrada a'],
        'Mid Stairs':       ['mid stairs', 'chafariz'],
        'Baloons':          ['baloons', 'balao', 'balão'],
        'T Steps':          ['t steps', 'passagem tr'],
        'Toxic':            ['toxic', 'toxico', 'tóxico'],
        'Banana':           ['banana', 'rua'],
        'Long':             ['long', 'fundo'],
        'Water':            ['water', 'agua', 'água'],
        'Dice':             ['dice', 'atras do default', 'atrás do default','caixa', 'caixa gorda', 'alvo'],
        'Fountain':         ['fountain', 'fonte'],
        'Divider':          ['divider', 'divisor'],
        'Short':            ['short', 'cimento'],
        'Short Pipe':       ['short pipe', 'canudo'],
        'Playground':       ['playground', 'parquinho'],
        'Van':              ['van', 'swat', 'carro forte'],
    },
    'dust2': {
        'A Cross':      ['a cross', 'cross', 'passagem a'],
        'B Door':       ['b door', 'porta b', 'portao b'],
        'CT Spawn':     ['ct spawn', 'spawn ct', 'base ct'],
        'Long Corner':  ['long corner', 'esquina fundo', 'esquina'],
        'Long Door':    ['long door', 'porta fundo'],
        'Mid':          ['mid', 'meio'],
        'Mid Doors':    ['mid doors', 'porta do meio', 'portas do meio'],
        'Short':        ['short', 'l', 'curto'],
        'Tunnel':       ['tunnel', 'tunel', 'túnel', 'escuro'],
        'Window':       ['window', 'janela', 'buraco'],
        'XBox':         ['xbox', 'caixa gorda', 'caixinha'],
        'A Site':       ['a site', 'asite', 'a', 'bomb a', 'bomba a'],
        'B Site':       ['b site', 'bsite', 'b', 'bomb b', 'bomba b'],
        'Long':         ['long', 'fundo'],
        'Long Doors':   ['long doors', 'portas do fundo'],
        'Lower Tunnel': ['lower tunnel', 'escuro baixo', 'tunel baixo'],
        'Car':          ['car', 'carro'],
        'Goose':        ['goose', 'newba'],
},
    'inferno': {
        'A Site':           ['a site', 'asite', 'bomb a', 'bomba a', 'a'],
        'B Site':           ['b site', 'bsite', 'bomb b', 'bomba b', 'b'],
        'B Entry':          ['b entry', 'entrada b', 'entrada da b'],
        'Balcony':          ['balcony', 'varanda', 'sacada'],
        'Banana':           ['banana'],
        'Deep Banana':      ['deep banana', 'fundo da banana', 'fundo banana'],
        'Car':              ['car', 'carro', 'carrocinha'],
        'Over Car':         ['over car', 'em cima do carro', 'cima do carro'],
        'Coffin':           ['coffin', 'caixao', 'caixão'],
        'Connector':        ['connector', 'arco', 'ligacao', 'ligação'],
        'CT':               ['ct', 'base ct', 'base'],
        'Library':          ['library', 'biblioteca', 'biblio'],
        'Long':             ['long', 'nip', 'longe'],
        'Mid':              ['mid', 'meio'],
        '2nd Mid':          ['2nd mid', 'meio falso', 'segundo meio'],
        'Moto':             ['moto', 'cemiterio', 'cemitério'],
        'Pit':              ['pit', 'areia', 'fosso'],
        'Ramp':             ['ramp', 'rampa'],
        'Short':            ['short', 'xuxa', 'curto'],
        'Boiler':           ['boiler', 'campanario', 'campanário', 'caldeira'],
        '1st Oranges':      ['1st oranges', 'fechado', 'laranja 1'],
        '2nd Oranges':      ['2nd oranges', 'btt', 'laranja 2'],
        'B Default':        ['b default', 'b padrao', 'b padrão'],
        'Dark':             ['dark', 'escuro', 'canto escuro'],
        'Halfwall':         ['halfwall', 'meia parede', 'mureta'],
        'Roof':             ['roof', 'telhado'],
        'Sandbags':         ['sandbags', 'sacos de areia', 'sacos', 'cimento'],
        'Brackets':         ['brackets', 'l do meio', 'ele do meio', 'l'],
        'T Spawn':          ['t spawn', 'base tr', 'base terro'],
        'Fountain':         ['fountain', 'chafariz', 'fonte'],
        'Apps':             ['apps', 'apartamento', 'aps', 'apto'],
    },
    'nuke': {
        'A Site':           ['a site', 'asite', 'bomb a', 'bomba a', 'a'],
        'B Site':           ['b site', 'bsite', 'bomb b', 'bomba b', 'b'],
        'T Spawn':          ['t spawn', 'base tr', 'base terro', 'spawn'],
        'B Double Doors':   ['b double doors', 'porta dupla', 'portao duplo', 'portão duplo'],
        'Cross 1':          ['cross 1', 'passagem fora 1', 'passagem 1'],
        'Cross 2':          ['cross 2', 'passagem fora 2', 'passagem 2'],
        'Door':             ['door', 'porta de metal', 'porta metal', 'portinha','metal'],
        'Garage':           ['garage', 'garagem'],
        'Heaven':           ['heaven', 'ceu', 'céu'],
        'Hut':              ['hut', 'casinha'],
        'Lobby':            ['lobby', 'miolo'],
        'Locker':           ['locker', 'vidro', 'vestiario', 'vestiário'],
        'Main':             ['main', 'terra', 'principal'],
        'Outside':          ['outside', 'lado de fora', 'fora', 'rua'],
        'Ramp':             ['ramp', 'rampa'],
        'Secret Cross 1':   ['secret cross 1', 'passagem secret 1', 'secret 1'],
        'Secret Cross 2':   ['secret cross 2', 'passagem secret 2', 'secret 2'],
        'Silo':             ['silo', 'caixa dagua', 'caixa dágua', 'marshmallow'],
        'Trophy':           ['trophy', 'trofeu', 'troféu', 'copa','radio'],
        'Vent':             ['vent', 'duto', 'dutos'],
        'Dark':             ['dark', 'batman', 'escuro'],
        'Mustang':          ['mustang', 'vovo', 'vovó'],
        'Red':              ['red', 'vermelho', 'caixa vermelha'],
        'Secret Stairs':    ['secret stairs', 'escada do secret', 'escada secret'],
        'Ruuf':             ['ruuf', 'roof', 'telhado'],
    },
    'anubis': {
        'A Site':           ['a site', 'asite', 'bomb a', 'bomba a', 'a'],
        'B Site':           ['b site', 'bsite', 'bomb b', 'bomba b', 'b'],
        'B Main':           ['b main', 'principal b', 'entrada b'],
        'Bricks':           ['bricks', 'tijolo', 'tijolos'],
        'Camera':           ['camera', 'câmera'],
        'Canals':           ['canals', 'canais', 'agua', 'água'],
        'Connector':        ['connector', 'ligacao', 'ligação', 'conect'],
        'CT':               ['ct', 'base ct', 'base'],
        'Dark':             ['dark', 'escuro', 'canto'],
        'Heaven':           ['heaven', 'ceu', 'céu'],
        'Main':             ['main', 'principal a', 'entrada a'],
        'Mid Temple':       ['mid temple', 'templo meio', 'templo do meio'],
        'Ruins':            ['ruins', 'ruinas', 'ruínas'],
        'Stairs':           ['stairs', 'escada'],
        'Temple':           ['temple', 'templo'],
        'Window':           ['window', 'janela', 'janelao', 'janelão'],
        'Mid Doors':        ['mid doors', 'portas do meio', 'porta do meio'],
        'Pit':              ['pit', 'fosso', 'areia'],
        'Pillar':           ['pillar', 'pilar'],
        'Boat':             ['boat', 'barco'],
        'Alley':            ['alley', 'beco'],
        'Long':             ['long', 'fundo'],
        'Top Mid':          ['top mid', 'topo meio', 'topo'],
    },
}

#usado para os menus
NOMES_PT = {
    'mirage': {
        'Apps':             'Tapete / Apartamento',
        'Deep Apps':        'Cozinha',
        'Firebox':          'Caixa de Fogo',
        'Window':           'Janela',
        'Short':            'L',
        'Connector':        'Ligação',
        'Catwalk':          'Passarela',
        'Jungle':           'Jungle',
        'Jungle+Connector': 'Passagem',
        'Kitchen Door':     'Porta do Mercado',
        'Kitchen Window':   'Janela do Mercado',
        'Left Arch':        'Arco da Esquerda',
        'Right Arch':       'Arco da Direita',
        'Stairs':           'Cabeçinha',
        'Palace':           'Palácio',
        'Ramp':             'Rampa',
        'B Site':           'Bomb B',
        'A Site':           'Bomb A',
        'Top Mid':          'Top Mid',
        'Ramp':             'Caverna',
        'Ticket':           'Boltz',
        'Ladder Room':      '3d / Moscow',
        'Mid Boxes':        'Carroça',
        'Mid':              'Meio',
        'Over Chair':       'Cadeira',
        'Over Palm':        'Palmeira',
        'Over Ramp':        'Rampa',
        'Dark':             'Areia',
        'Underpass':        'Caminho de Rato',
        'Bench':            'Banco',
        'Sandwitch':        'Sanduiche',
        
        
    },
    'overpass': {
        'Bank':             'Banco',
        'Bridge':           'Passagem',
        'Heaven':           'Céu',
        'Monster':          'Sapão',
        'Toilets':          'Banheiro',
        'Trash':            'Lixo',
        'B Backsite':       'Piscina',
        'B Site':           'Bomb B',
        'A Site':           'Bomb A',
        'Truck':            'Caminhão',
        'Connector Doors':  'Ligação',
        'Monster Exit':     'Saída do Sapão',
        'Main Stairs':      'Entrada da A',
        'Mid Stairs':       'Chafariz',
        'Baloons':          'Balão',
        'T steps':          'Passagem TR',
        'Toxic':            'Tóxico',
        'Banana':           'Rua',
        'Long':             'Fundo',
        'Water':            'Água',
        'Dice':             'Alvo',
        'Fountain':         'Fonte',
        'Divider':          'Divisor',
        'Short':            'Cimento',
        'Short Pipe':       'Canudo',
        'Playground':       'Parquinho',
        'Van':              'Swat',
        
        
    },
    
    
    'dust2': {
        'A Cross':      'Passagem A',
        'B Door':       'Porta B',
        'CT Spawn':     'Base CT',
        'Long Corner':  'Esquina Fundo',
        'Long Door':    'Porta Fundo',
        'Mid':          'Meio',
        'Mid Doors':    'Porta do Meio',
        'Short':        'L',
        'Tunnel':       'Escuro',
        'Window':       'Buraco',
        'XBox':         'Caixa Gorda',
        'A Site':       'Bomb A',
        'B Site':       'Bomb B',
        'Long':         'Fundo',
        'Long Doors':   'Portas do Fundo',
        'Lower Tunnel': 'Escuro Baixo',
        'Car':          'Carro',
        'Goose':        'Newba',
    },
    
    'inferno': {
    'A Site':            'Bomb A',
    'B Site':            'Bomb B',
    'B Entry':           'Entrada B',
    'Balcony':           'Varanda',
    'Banana':            'Banana',
    'Deep Banana':       'Fundo da Banana',
    'Car':               'Carro',
    'Over Car':          'Em cima do Carro',
    'Coffin':            'Caixão',
    'Connector':         'Arco',
    'CT':                'Base CT',
    'Library':           'Biblioteca',
    'Long':              'NIP',
    'Mid':               'Meio',
    '2nd Mid':           'Meio Falso',
    'Moto':              'Moto',
    'Pit':               'Areia',
    'Ramp':              'Rampa',
    'Short':             'Xuxa',
    'Boiler':            'Campanário',
    '1st Oranges':       'Fechado',
    '2nd Oranges':       'BTT',
    'B Default':         'B Padrão',
    'Dark':              'Escuro',
    'Halfwall':          'Meia Parede',
    'Roof':              'Telhado',
    'Sandbags':          'Cimento',
    'Brackets':          'L do Meio',
    'T Spawn':           'Base TR',
    'Fountain':          'Chafariz',
    'Apps':              'Apartamento',
},
    'ancient': {
        'A Site':            'Bomb A',
        'B Site':            'Bomb B',
        'Mid':               'Meio',
        'B Alley':           'Beco',
        'B Doors':           'Portas B',
        'Cave':              'Escuro',
        'Cheetah':           'Passagem Escuro',
        'CT':                'Base CT',
        'Donut':             'Rosquinha',
        'Elbow':             'Cotovelo',
        'Long':              'Sol',
        'Main':              'Principal',
        'Ramp':              'Rampa',
        'Short':             'Sombra',
        'Temple':            'Templo',
        'Window':            'Janela',
        'A Backsite':        'Fundo do A',
        'Boost':             'Pezinho',
        'Ninja':             'Ninja',
        'Pit':               'Fosso',
        'Outside A':         'Lado de Fora A',
        'T Spawn':           'Base TR',
        'Yard':              'Pátio',
        'Outside B':         'Lado de Fora B',
    },
    'nuke': {
        'A Site':            'Bomb A',
        'B Site':            'Bomb B',
        'T Spawn':           'Base TR',
        'B Double Doors':    'Porta Dupla',
        'Cross 1':           'Passagem Fora 1',
        'Cross 2':           'Passagem Fora 2',
        'Door':              'Porta de Metal',
        'Garage':            'Garagem',
        'Heaven':            'Céu',
        'Hut':               'Casinha',
        'Lobby':             'Miolo',
        'Locker':            'Vidro',
        'Main':              'Terra',
        'Outside':           'Lado de Fora',
        'Ramp':              'Rampa',
        'Secret Cross 1':    'Passagem Secret 1',
        'Secret Cross 2':    'Passagem Secret 2',
        'Silo':              'Silo',
        'Trophy':            'Troféu',
        'Vent':              'Duto',
        'Dark':              'Batman',
        'Mustang':           'Vovó',
        'Red':               'Vermelho',
        'Secret Stairs':     'Escada do Secret',
        'Ruuf':              'Telhado',
    },
    'anubis': {
        'A Site':            'Bomb A',
        'B Site':            'Bomb B',
        'B Main':            'Principal B',
        'Bricks':            'Tijolo',
        'Camera':            'Câmera',
        'Canals':            'Canais',
        'Connector':         'Ligação',
        'CT':                'Base CT',
        'Dark':              'Escuro',
        'Heaven':            'Céu',
        'Main':              'Principal A',
        'Main Exit':         'Saída do A',
        'Mid Temple':        'Templo Meio',
        'Ruins':             'Ruínas',
        'Stairs':            'Escada',
        'Temple':            'Templo A',
        'Window':            'Janela',
        'Mid Doors':         'Portas do Meio',
        'Over Mid Door':     'Cima da Porta',
        'B Default':         'B Padrão',
        'Pit':               'Fosso',
        'Pillar':            'Pilar',
        'Boat':              'Barco',
        'Alley':             'Beco',
        'Long':              'Fundo',
        'Top Mid':           'Topo Meio',
    },
}

THROW_PT = {
    'left click':             'clique esquerdo',
    'left jumpthrow':         'jumpthrow esquerdo',
    'left+right click':       'clique esquerdo+direito',
    'left+right jumpthrow':   'jumpthrow esquerdo+direito',
    'right click':            'clique direito',
    'right jumpthrow':        'jumpthrow direito',
}

MODEL_PT = {
    'stand':   'em pé',
    'crouch':  'agachado',
}

DESCRICOES = {
    'Loose lineup':            'Alinhamento livre / não rigoroso',
    'Aim at middle':           'Mire no meio',
    'Jumpthrow':               'Pular e tacar (jumpthrow)',
    'Crouch':                  'Agache',
    'Stand':                   'Fique em pé',
    'Run forward':             'Corra para frente',
    'Max velocity reached':    'Velocidade máxima atingida',
    'Left click':              'Botão esquerdo',
    'Right click':             'Botão direito',
    'Align vertically':        'Alinhe verticalmente',
    'Align horizontally':      'Alinhe horizontalmente',
    'Break glass':             'Quebre o vidro',
    'Tap W':                   'Toque no W',
}