# Generated by Django 6.0.5 on 2026-05-06 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Granada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('smoke', 'Smoke'), ('flash', 'Flash'), ('molotov', 'Molotov'), ('he', 'HE Grenade')], max_length=20)),
                ('destino', models.CharField(max_length=200)),
                ('origem', models.CharField(max_length=200)),
                ('lado', models.CharField(choices=[('tr', 'Terrorista'), ('ct', 'Contra-Terrorista'), ('ambos', 'Ambos')], max_length=10)),
                ('video_url', models.URLField()),
                ('thumbnail', models.URLField(blank=True)),
                ('origem_url', models.URLField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('mapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nades.mapa')),
            ],
        ),
    ]
