# Generated by Django 6.0.5 on 2026-05-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='granada',
            name='air_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='granada',
            name='model_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='granada',
            name='move_keys',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='granada',
            name='posicao',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='granada',
            name='throw_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
