# Generated by Django 6.0.5 on 2026-05-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nades', '0002_granada_air_time_granada_model_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='granada',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
